### ISSUE TITLE
Implement support for multiple-table syntax on delete statements

### ISSUE THREAD

**Issue by Cruiser79** [elgris/sqrl#6]
Currently you are not able to create a delete statement, to delete from multiple tables, like in mysql documentation described: http://dev.mysql.com/doc/refman/5.7/en/delete.html#idm140368126356160
Is it possible to implement it?

**Comment by elgris** [comment]
Hi @Cruiser79!

Thanks, I'll take a look at my spare time. But if you have any idea or ready-to-submit pull request, it would be great!

**Comment by Cruiser79** [comment]
Hi elgris,
to make a pull request, it is not clear to me, what is the best way, for the right method construct.
The main problem is, that in https://github.com/elgris/sqrl/blob/master/delete.go the sql is build with

`sql.WriteString("DELETE FROM ")`

Here we need somthing like

`sql.WriteString("DELETE ")`
`sql.WriteString(b.deleteTables)`
`sql.WriteString(" FROM ")`

and set deleteTables in an own method. If it is empty, everthing is, like before.
But i don't know, if this is the best way for this!?
