### ISSUE TITLE
Cannot QueryRow() with MySQL driver

### ISSUE THREAD

**Issue by michael2m** [elgris/sqrl#8]
Executing QueryRow() against a SelectBuilder doesn't work for MySQL, because it is not a QueryRower.

**Comment by elgris** [comment]
thanks @michael2m! I'll check ASAP

**Comment by elgris** [comment]
Hi @michael2m!
You're right, `sql.DB` does not implement `QueryRow()`. But you can wrap it in order to provide necessary functionality. The wrapper may look like this:
```
type SqlWrapper struct {
	db *sql.DB
}

func (w SqlWrapper) QueryRow(query string, args ...interface{}) RowScanner {
	return w.db.QueryRow(query, args...)
}
```

**Comment by michael2m** [comment]
Acceptable.

**Comment by elgris** [comment]
closing for now
