### ISSUE TITLE
Context not supported, e.g. for cancelation

### ISSUE THREAD

**Issue by michael2m** [elgris/sqrl#9]
Allow a context.Context be passed into Query(...) and QueryRow(...) etc.

**Comment by elgris** [comment]
@michael2m please take a look at the PR https://github.com/elgris/sqrl/pull/10

I'll take another look tomorrow with fresh mind.

**Comment by michael2m** [comment]
I think that should do it.

**Comment by elgris** [comment]
merged. Please try it out. 
And thanks for your feedback :)
